[tools]
bat = "latest"
bottom = "latest"
bun = "latest"
direnv = "latest"
docker-compose = { version = "latest", os = ["linux"] }
duf = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
jq = "latest"
lazydocker = "latest"
lazygit = "latest"
ni = "latest"
node = "latest"
opencode = { version = "latest", os = ["linux"] }
pandoc = "latest"
ripgrep = "latest"
rust = "latest"
tree-sitter = { version = "latest", os = ["linux"] }
yazi = "latest"
yq = "latest"
zoxide = "latest"
