[tools]
bat = "latest"
bottom = "latest"
btop = "latest"
bun = "latest"
direnv = "latest"
# docker-cli = "latest"
docker-compose = "latest"
duf = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
jq = "latest"
lazydocker = "latest"
lazygit = "latest"
ni = "latest"
node = "latest"
opencode = "latest"
pandoc = "latest"
ripgrep = "latest"
rust = "latest"
tree-sitter = "latest"
yazi = "latest"
yq = "latest"
zoxide = "latest"
